version: '3.1'

services:
  mongo:
    image: mongo:5.0
    hostname: ${RS:-rs0}
    container_name: ${RS:-rs0}
    command: mongod --replSet ${RS:-rs0} --port ${PORT:-27017}
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:${PORT:-27017}
  mongo_config:
    image: mongo:5.0
    hostname: rsc
    container_name: rsc
    command: config
    volumes:
      - ./mongo-config.sh:/bin/config
    env_file:
      - .env
